name: Deploy to EKS

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      ecr_repo:
        required: true
        type: string
      eks_cluster_name:
        required: true
        type: string
      deployment_file:
        required: false
        type: string
        default: './deployment.template.yaml'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B (this repo)
        uses: actions/checkout@v4
        with:
          repository: AmanjotSinghSaini-int/ci-templates
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ inputs.eks_cluster_name }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Substitute image tag in deployment file
        run: |
          IMAGE="${{ inputs.ecr_repo }}:${{ inputs.image_tag }}"
          sed "s|{{IMAGE}}|$IMAGE|g" deployment.template.yaml > final-deployment.yaml
          cat final-deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f final-deployment.yaml
