name: Docker Build Reusable Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: './Dockerfile'
      context:
        required: false
        type: string
        default: '.'
      build_args:
        required: false
        type: string
        default: ''
      run_trivy:
        required: false
        type: boolean
        default: true
      run_gitleaks:
        required: false
        type: boolean
        default: true
      continue_on_gitleaks_error:
        required: false
        type: boolean
        default: true
      run_owasp:
        required: false
        type: boolean
        default: true

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          echo "Building Docker image: ${{ inputs.image_name }}"
          docker build \
            -t ${{ inputs.image_name }} \
            -f ${{ inputs.dockerfile_path }} \
            ${{ inputs.build_args }} \
            ${{ inputs.context }}

      - name: Dockerized Trivy scan and generate txt report
        if: ${{ inputs.run_trivy }}
        run: |
          echo "Running Trivy inside Docker"
          mkdir -p trivy-reports
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/trivy-reports:/output \
            aquasec/trivy:latest \
            image ${{ inputs.image_name }} \
            --format table \
            --ignore-unfixed \
            --vuln-type os,library \
            -o /output/trivy-report.txt

      - name: Upload Trivy txt Report
        if: ${{ inputs.run_trivy }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-reports/trivy-report.txt


      - name: Dockerized Gitleaks scan and generate report
        if: ${{ inputs.run_gitleaks }}
        continue-on-error: ${{ inputs.continue_on_gitleaks_error }}
        run: |
          echo "Running Gitleaks inside Docker"
          mkdir -p gitleaks-reports
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -v ${{ github.workspace }}/gitleaks-reports:/output \
            zricethezav/gitleaks:latest detect \
            --source="/repo" \
            --report-format="json" \
            --report-path="/output/gitleaks-report.json"

      - name: Upload Gitleaks Report
        if: ${{ inputs.run_gitleaks }}
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-reports/gitleaks-report.json

      

      - name: Run OWASP Dependency Check (with caching)
        if: ${{ inputs.run_owasp }}
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MyProject"
          path: "."
          format: "HTML"
          out: "dependency-check-reports"

      - name: Upload OWASP Dependency Check Report
        if: ${{ inputs.run_owasp }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-html-report
          path: dependency-check-reports/dependency-check-report.html
