name: Docker Build Reusable WorkflowMore actions

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: './Dockerfile'
      context:
        required: false
        type: string
        default: '.'
      build_args:
        required: false
        type: string
        default: ''

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout source code
        uses: actions/checkout@v4

      - name:  Build Docker image
        run: |
          echo " Building Docker image: ${{ inputs.image_name }}"
          docker build \
            -t ${{ inputs.image_name }} \
            -f ${{ inputs.dockerfile_path }} \
            ${{ inputs.build_args }} \
            ${{ inputs.context }}

      - name:  Dockerized Trivy scan and generate report
        run: |
          echo " Running Trivy inside Docker"
          mkdir -p trivy-reports
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/trivy-reports:/output \
            aquasec/trivy:latest \
            image ${{ inputs.image_name }} \
            --format table \
            --ignore-unfixed \
            --vuln-type os,library \
            -o /output/trivy-report.txt

      - name:  Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-reports/trivy-report.txt

      - name:  Dockerized Gitleaks scan and generate report
        run: |
          echo " Running Gitleaks inside Docker"
          mkdir -p gitleaks-reports
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -v ${{ github.workspace }}/gitleaks-reports:/output \
            zricethezav/gitleaks:latest detect \
            --source="/repo" \
            --report-format="json" \
            --report-path="/output/gitleaks-report.json"

      - name:  Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-reports/gitleaks-report.json

      - name:  OWASP Dependency Check scan
        run: |
          echo " Running OWASP Dependency Check"
          mkdir -p dependency-check-reports
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/dependency-check-reports:/report \
            owasp/dependency-check:latest \
            --project "MyProject" \
            --scan /src \
            --format JSON \
            --out /report

      - name:  Upload OWASP Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-reports/dependency-check-report.json
